// <auto-generated />
namespace KOExamApp.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201801032054071_addRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
